name: lint php documentation

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    lint-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: lint php documentation
              uses: sudo-bot/action-doctum@dev
              with:
                  config-file: scripts/doctum.php
                  method: "parse"
                  cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
